from typing import List

def read_faces(path: str) -> List[List[int]]: ...
def read_faces_from_text(text: str) -> List[List[int]]: ...
def read_int_groups_from_text(text: str) -> List[List[int]]: ...  # deprecated alias
def read_points(path: str) -> List[List[float]]: ...
def read_points_from_text(text: str) -> List[List[float]]: ...
def read_boundary(path: str) -> dict[str, dict[str, int]]: ...

__all__: list[str]
__version__: str